# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='scoring_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='criterion',
            name='weighting_notes',
            field=models.TextField(default=''),
        ),
    ]
