# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteron',
            name='name',
            field=models.CharField(default='?', max_length=200),
            preserve_default=False,
        ),
    ]
