# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-22 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criteron_name'),
    ]

    operations = [
        migrations.RenameModel('criteron', 'criterion')
    ]
