# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160622_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), unique=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), unique=True),
        ),
        migrations.AddField(
            model_name='option',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), unique=True),
        ),
        migrations.AddField(
            model_name='score',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), unique=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criterion'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criterion'),
        ),
    ]
