# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160622_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['category__name', 'name'], 'verbose_name_plural': 'criteria'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AlterField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.Criterion'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.Criterion'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('user', 'option', 'criterion')]),
        ),
    ]
