# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160624_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={},
        ),
        migrations.AlterField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.Criterion'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.Criterion'),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together=set([('user', 'criterion')]),
        ),
    ]
