# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160625_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['category__name', 'order_num'], 'verbose_name_plural': 'criteria'},
        ),
        migrations.AddField(
            model_name='criterion',
            name='order_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.Criterion'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.Criterion'),
        ),
    ]
